nlp_engine_name: spacy
models:
  - lang_code: de
    model_name: /app/models/de_with_address
ner_model_configuration:
  labels_to_ignore: [O, MISC]
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    LOC: LOCATION
    ORG: ORGANIZATION
    ADDRESS: ADDRESS